version: '3'
services:
  redmine:
    build: .
    restart: always
    container_name: redmine_container
    environment:
      - REDMINE_DB_POSTGRES=db
      - REDMINE_DB_USERNAME=postgres
      - REDMINE_DB_PASSWORD=postgres
      - REDMINE_PLUGINS_MIGRATE=true
      - VIRTUAL_HOST="{$VIRTUAL_HOST}"
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./redmine/files:/usr/src/redmine/files
    links:
      - db
  db:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  https-portal:
    image: steveltn/https-portal:latest
    ports:
      - '80:80'
      - '443:443'
    links:
      - redmine
    restart: always
    environment:
      DOMAINS: "{$DOMAINS}"
      STAGE: 'production'
      ORCE_RENEW: 'true'
